server:
  port: 8081

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mango?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
#    username: root
#    password: 123456

#替换成阿里的druid数据源配置
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mango?useUnicode=
            true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: 123456
      filters: stat,wall,log4j,config #配置监控统计拦截的filter
      max-active: 100  #最大连接数
      initial-size: 1   #初始化大小
      max-wait: 60000   #获取连接等待超时时间
      min-idle: 1   #最小连接数
      time-between-eviction-runs-millis: 60000   #间隔多久进行一次检测
      min-evictable-idle-time-millis: 300000  #一个连接在池中最小生存时间
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20